import Head from "next/head";
import Message from "../components/Message";
import { useEffect, useState } from "react";
import { db } from "../utils/firebase";
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import Loader from "../components/Loader";

export default function Home() {
  const [allPosts, setAllPosts] = useState([]);
  const [loading, setLoading] = useState(false);

  const getAllPosts = async () => {
    setLoading(true);
    const collectionRef = collection(db, "posts");
    //fetch data by giving a query
    const q = query(collectionRef, orderBy("timeStamp", "desc"));
    //get real time data using snapshot
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setAllPosts(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    });
    setLoading(false);
    return unsubscribe;
  };

  console.log({ loading });

  useEffect(() => {
    getAllPosts();
  }, []);

  if (loading) return <Loader />;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-12 text-lg font-medium">
        <h2>See what other people are saying!</h2>
      </div>
      {allPosts.map((post) => (
        <Message key={post.id} post={post} />
      ))}
    </div>
  );
}
